import { Arm, defaultConfig, homeState } from '../src/core/arm.js';
import { V3, Quat, Transform, rad } from '../src/core/mathx.js';
const arm = new Arm(defaultConfig());
const ext = { force: V3.zero(), torque: V3.zero() };
const anchor = V3.new(0.1691, 0.6437, 0.0516), axis = V3.norm(V3.new(0.3686, 0.9151, -0.1635));
const p = V3.add(anchor, V3.scale(axis, -0.004));
const seed = homeState();
const seg = arm.ik({ p, q: Quat.fromYTo(axis) }, seed, 40, { axisWeight: 0.3 });
const show = (s) => s.map(x => `${rad(x.bend).toFixed(1)}°/${rad(x.plane).toFixed(0)}°/${(x.compress*1000).toFixed(1)}`).join(' | ');
console.log('maxBend/seg', rad(arm.maxBendPerSegment).toFixed(1), 'maxComp/seg', (arm.maxCompression/3*1000).toFixed(1));
console.log('ik      ', show(seg));
const cables = arm.cableTargets(seg);
console.log('cables mm', cables.map(c => (c*1000).toFixed(1)).join(' '));
const rt = arm.shapeFromCables({ seg: seed.seg, cables });
console.log('rt      ', show(rt));
console.log('loaded  ', show(arm.predictLoaded(rt, seed, ext)));
const st = homeState();
st.cableCmd = cables;
for (let i = 0; i < 240*4; i++) arm.step(st, 1/240, ext, { speed: 0 });
console.log('settled ', show(st.seg));
console.log('cables settled', st.cables.map(c=>(c*1000).toFixed(1)).join(' '));
console.log('err ik', (V3.len(V3.sub(arm.fk(seg,0,0).p, p))*1000).toFixed(1), 'err rt', (V3.len(V3.sub(arm.fk(rt,0,0).p, p))*1000).toFixed(1), 'err settled', (V3.len(V3.sub(st.tool.p, p))*1000).toFixed(1));
