/**
 * truncData.js — GENERATED by `node tools/trunc-data.mjs`. Do not edit by hand.
 *
 * The two TRUNC cells' structural features, straight from the authors' data
 * (TransformativeRoboticsLab/TRUNC: `matlab/instron` measurements and the
 * `matlab/ansys` design-space sweep; the raw files are in `data/trunc/`).
 *
 * The pair that matters is `bend.k` against `twist.k`: a TRUNC passes rotation
 * through almost rigidly (twist) while giving way in bending and extension. The
 * app's joints use these measured numbers for their transmission, instead of an
 * invented stiffness.
 */
export const TRUNC_DATA = {
  "source": "TransformativeRoboticsLab/TRUNC — matlab/instron, matlab/ansys (data/trunc/*.csv)",
  "cells": {
    "equatorial": {
      "rated": {
        "bendDeg": 45,
        "twistDeg": 65,
        "stroke": 20
      },
      "bend": {
        "k": 0.4781217151168453,
        "kPerRad": 27.394356369751527,
        "r2": 0.9121224637838612,
        "samples": 995,
        "testedDeg": 20.0025,
        "momentAtTested": 9.5636296066247,
        "momentAtRated": 21.51547718025804
      },
      "twist": {
        "k": 5.410083940630498,
        "kPerRad": 309.97497660963256,
        "r2": 0.9994590392252823,
        "samples": 989,
        "testedDeg": 64.9992,
        "momentAtTested": 351.6511280738299,
        "momentAtRated": 351.6554561409824
      },
      "axial": {
        "k": 0.05621104254213793,
        "r2": 0.9572208177631529,
        "samples": 380,
        "testedMm": 15.0003,
        "forceAtTested": 0.8431825014448315
      },
      "twistBendRatio": 11.315285981747053
    },
    "truss": {
      "rated": {
        "bendDeg": 45,
        "twistDeg": 65,
        "stroke": 20
      },
      "bend": {
        "k": 0.5014778696072544,
        "kPerRad": 28.732565447707493,
        "r2": 0.9795341775332126,
        "samples": 995,
        "testedDeg": 20.0034,
        "momentAtTested": 10.031262416901752,
        "momentAtRated": 22.566504132326447
      },
      "twist": {
        "k": 26.098754134358636,
        "kPerRad": 1495.348462448358,
        "r2": 0.9950277914565242,
        "samples": 987,
        "testedDeg": 64.9997,
        "momentAtTested": 1696.411189107071,
        "momentAtRated": 1696.4190187333113
      },
      "axial": {
        "k": 0.20545489444828155,
        "r2": 0.9433561059704406,
        "samples": 380,
        "testedMm": 15.0003,
        "forceAtTested": 3.0818850531925577
      },
      "twistBendRatio": 52.043680720743595
    }
  },
  "fea": {
    "equatorial": [
      {
        "d": 28,
        "material": "Neoprene Rubber",
        "kBend": 0.000021569158761001104,
        "kTwist": 0.0001498688535933512,
        "ratio": 6.948293869686146
      },
      {
        "d": 28,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.14945513416331407,
        "kTwist": 0.46149587160085137,
        "ratio": 3.087855590806008
      },
      {
        "d": 28,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.482917169273937,
        "kTwist": 9.28128271176299,
        "ratio": 19.219202178537866
      },
      {
        "d": 28,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.5228170997754025,
        "kTwist": 28.749260665843185,
        "ratio": 54.98913612082239
      },
      {
        "d": 42,
        "material": "Neoprene Rubber",
        "kBend": 0.000012514485355302416,
        "kTwist": 0.00008343960944592424,
        "ratio": 6.667442333980653
      },
      {
        "d": 42,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.10643710704138325,
        "kTwist": 0.28841484889948643,
        "ratio": 2.709720856912706
      },
      {
        "d": 42,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.45238341082408334,
        "kTwist": 5.210982022875571,
        "ratio": 11.518950293475609
      },
      {
        "d": 42,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.5159725703780583,
        "kTwist": 16.102969669702134,
        "ratio": 31.208964573258854
      },
      {
        "d": 56,
        "material": "Neoprene Rubber",
        "kBend": 0.000007472203054225283,
        "kTwist": 0.000049343330231348355,
        "ratio": 6.603585297838813
      },
      {
        "d": 56,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.08467359914785526,
        "kTwist": 0.21702018360334407,
        "ratio": 2.5630206556401127
      },
      {
        "d": 56,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.431596817748454,
        "kTwist": 3.531578936769736,
        "ratio": 8.18258798846852
      },
      {
        "d": 56,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.5207417784593937,
        "kTwist": 10.876228099941013,
        "ratio": 20.886029410043037
      },
      {
        "d": 70,
        "material": "Neoprene Rubber",
        "kBend": 0.00000909281941891505,
        "kTwist": 0.00004308751358390354,
        "ratio": 4.7386307369386556
      },
      {
        "d": 70,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.08072162142363383,
        "kTwist": 0.2000503515390544,
        "ratio": 2.4782746928381605
      },
      {
        "d": 70,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.42966873826341456,
        "kTwist": 3.0045545666974274,
        "ratio": 6.992723228692152
      },
      {
        "d": 70,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.5378995863407324,
        "kTwist": 9.184438130112085,
        "ratio": 17.074633190541633
      },
      {
        "d": 84,
        "material": "Neoprene Rubber",
        "kBend": 0.000009393457238368893,
        "kTwist": 0.00003564963011556034,
        "ratio": 3.795155416255522
      },
      {
        "d": 84,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.07666866729363431,
        "kTwist": 0.18449923764454418,
        "ratio": 2.4064489987536657
      },
      {
        "d": 84,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.42785022543963175,
        "kTwist": 2.5620513651996206,
        "ratio": 5.988196833522804
      },
      {
        "d": 84,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.558502453368961,
        "kTwist": 7.785047631746216,
        "ratio": 13.93914670344915
      },
      {
        "d": 98,
        "material": "Neoprene Rubber",
        "kBend": 0.000008410622175818963,
        "kTwist": 0.0000310519824814725,
        "ratio": 3.6919958871471823
      },
      {
        "d": 98,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.07579136090747346,
        "kTwist": 0.17385714190587492,
        "ratio": 2.2938912802756075
      },
      {
        "d": 98,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.4372307078149285,
        "kTwist": 2.2774757365147096,
        "ratio": 5.208865012927505
      },
      {
        "d": 98,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.590530693458326,
        "kTwist": 6.887172406199271,
        "ratio": 11.662683214425165
      },
      {
        "d": 112,
        "material": "Neoprene Rubber",
        "kBend": 0.00000666798768309445,
        "kTwist": 0.000026668276826776962,
        "ratio": 3.9994490233372577
      },
      {
        "d": 112,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.06974459157330166,
        "kTwist": 0.16856476379327492,
        "ratio": 2.416886528270986
      },
      {
        "d": 112,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.4369207717827433,
        "kTwist": 2.071161044939321,
        "ratio": 4.7403583869187065
      },
      {
        "d": 112,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.6245790571372041,
        "kTwist": 6.214094727635172,
        "ratio": 9.949252471124874
      }
    ],
    "truss": [
      {
        "d": 28,
        "material": "Neoprene Rubber",
        "kBend": 0.00003762175419683321,
        "kTwist": 0.0005049383517087996,
        "ratio": 13.4214462480142
      },
      {
        "d": 28,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.14609887196174523,
        "kTwist": 1.950711562175706,
        "ratio": 13.35199605570181
      },
      {
        "d": 28,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.673173913752164,
        "kTwist": 43.067726848512486,
        "ratio": 63.977117901761595
      },
      {
        "d": 28,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 1.7023837854143185,
        "kTwist": 132.02646485274937,
        "ratio": 77.55387826407038
      },
      {
        "d": 42,
        "material": "Neoprene Rubber",
        "kBend": 0.000020229432097373465,
        "kTwist": 0.00025509764587199914,
        "ratio": 12.610222800328652
      },
      {
        "d": 42,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.11825090402835416,
        "kTwist": 1.038034366779832,
        "ratio": 8.77823620300554
      },
      {
        "d": 42,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.4781236941486734,
        "kTwist": 22.56639902559916,
        "ratio": 47.19782621478303
      },
      {
        "d": 42,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 1.0940957417215873,
        "kTwist": 69.31044571710424,
        "ratio": 63.34952515950981
      },
      {
        "d": 56,
        "material": "Neoprene Rubber",
        "kBend": 0.00001606147786904059,
        "kTwist": 0.00017241330242937422,
        "ratio": 10.734585187936574
      },
      {
        "d": 56,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.10816677757191781,
        "kTwist": 0.7500147041943306,
        "ratio": 6.933873052616933
      },
      {
        "d": 56,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.41708805633443574,
        "kTwist": 15.791232397725002,
        "ratio": 37.86066792826846
      },
      {
        "d": 56,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.8852121930614557,
        "kTwist": 48.480507730347426,
        "ratio": 54.767103424864004
      },
      {
        "d": 70,
        "material": "Neoprene Rubber",
        "kBend": 0.000012066568865323023,
        "kTwist": 0.00011589784141863353,
        "ratio": 9.60487133601843
      },
      {
        "d": 70,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.09948119681004347,
        "kTwist": 0.5883190917966306,
        "ratio": 5.913872275984065
      },
      {
        "d": 70,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.39783577778118134,
        "kTwist": 12.082346826762887,
        "ratio": 30.370186648744422
      },
      {
        "d": 70,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.8071439514241951,
        "kTwist": 37.14962616322028,
        "ratio": 46.02602311232122
      },
      {
        "d": 84,
        "material": "Neoprene Rubber",
        "kBend": 0.000011095429456494141,
        "kTwist": 0.00009779520698301377,
        "ratio": 8.814008269483825
      },
      {
        "d": 84,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.09579950686733892,
        "kTwist": 0.5147224985294934,
        "ratio": 5.372913863139922
      },
      {
        "d": 84,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.3925333228060386,
        "kTwist": 10.116345045994704,
        "ratio": 25.771939497206624
      },
      {
        "d": 84,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.768108909905234,
        "kTwist": 31.0526461001965,
        "ratio": 40.42739994257799
      },
      {
        "d": 98,
        "material": "Neoprene Rubber",
        "kBend": 0.0000058928633142681084,
        "kTwist": 0.00006798403535074504,
        "ratio": 11.536672704784879
      },
      {
        "d": 98,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.08076843345378747,
        "kTwist": 0.4174877558079291,
        "ratio": 5.168947049676272
      },
      {
        "d": 98,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.3793912815156396,
        "kTwist": 7.917233280431519,
        "ratio": 20.86825308373658
      },
      {
        "d": 98,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.725788567074027,
        "kTwist": 24.35022140811804,
        "ratio": 33.550020643456115
      },
      {
        "d": 112,
        "material": "Neoprene Rubber",
        "kBend": 0.00000894818481377853,
        "kTwist": 0.00007051962728667616,
        "ratio": 7.880886319881226
      },
      {
        "d": 112,
        "material": "Plastic, PET (amorphous)",
        "kBend": 0.08338715612234901,
        "kTwist": 0.40471804955002333,
        "ratio": 4.853481859438936
      },
      {
        "d": 112,
        "material": "Aluminum alloy, wrought, 6061, T6",
        "kBend": 0.3918552930678775,
        "kTwist": 7.197047144402193,
        "ratio": 18.36659417831448
      },
      {
        "d": 112,
        "material": "Carbon steel, 1095, hardened & tempered",
        "kBend": 0.7362789004103978,
        "kTwist": 22.0239291280314,
        "ratio": 29.912481691048576
      }
    ]
  },
  "flexShaft": {
    "curve": [
      {
        "strain": 0,
        "k": 63.367555555555555
      },
      {
        "strain": 0.1535771494740905,
        "k": 63.71644444444445
      },
      {
        "strain": 0.3071523690051144,
        "k": 63.406864197530865
      },
      {
        "strain": 0.4607295184792049,
        "k": 63.224271604938274
      },
      {
        "strain": 0.614308597896362,
        "k": 62.91659259259259
      },
      {
        "strain": 0.7678857473704526,
        "k": 62.474716049382714
      },
      {
        "strain": 0.9214628968445431,
        "k": 61.82004938271606
      },
      {
        "strain": 1.0750381163755671,
        "k": 61.01730864197531
      },
      {
        "strain": 1.2286152658496576,
        "k": 60.12859259259259
      },
      {
        "strain": 1.3821924153237481,
        "k": 59.11167901234568
      },
      {
        "strain": 1.5357676348547717,
        "k": 57.99427160493827
      },
      {
        "strain": 1.6893467142719292,
        "k": 56.88720987654321
      },
      {
        "strain": 1.8429315835182862,
        "k": 55.58296296296297
      },
      {
        "strain": 1.9964971533339766,
        "k": 54.29797530864198
      },
      {
        "strain": 2.150082022580334,
        "k": 52.92567901234568
      }
    ],
    "stiffnessAtRest": 63.367555555555555,
    "stiffnessAtMaxStrain": 52.92567901234568,
    "strainAtMax": 2.150082022580334,
    "retention": 0.8352173055806882
  },
  "inArm": {
    "truss": {
      "d": 56,
      "material": "Carbon steel, 1095, hardened & tempered",
      "kBend": 0.8852121930614557,
      "kTwist": 48.480507730347426,
      "ratio": 54.767103424864004
    },
    "equatorial": {
      "d": 84,
      "material": "Carbon steel, 1095, hardened & tempered",
      "kBend": 0.558502453368961,
      "kTwist": 7.785047631746216,
      "ratio": 13.93914670344915
    }
  }
};

/** The measured features of one cell kind: 'truss' | 'equatorial'. */
export const cellFeatures = (kind) => TRUNC_DATA.cells[kind === 'truss' ? 'truss' : 'equatorial'];

/**
 * Angular wind-up of a chain of `n` joints of this kind under `torque` (N·mm):
 * what the joint loses between commanded and transmitted rotation.
 */
export const windUpDeg = (kind, torque, n = 1) => torque * n / cellFeatures(kind).twist.k;

/** Kinematic constants of the arm's own model (matlab/training/kinematics.m). */
export const TRUNC_KINEMATICS = {
  length: 710,            // neutral arm length (mm), L_0
  toolLength: 83,         // wrist → tool (mm)
  cableRadius: 65,        // cable triangle radius (mm)
  segmentSplit: [3 / 7, 2 / 7, 2 / 7],
  cables: 9,
  activeJoints: 3,
  dof: 7,                 // six joint angles (Rx, Rz per stage) + one shared axial slide L
};

export default TRUNC_DATA;
